version: '3.8'

services:
  client:
    build: ./next-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
